
weather-api.api.forecast.url: "https://api.openweathermap.org/data/2.5/forecast?q={city}&appid={apiKey}&cnt={numberOfDays}"
weather-api.api.forecast.numberofdays: 3
#example - https://api.openweathermap.org/data/2.5/forecast?q=pune&appid=apikey&cnt=3
weather-api.api.key: d2929e9483efc82c82c32ee7e02d563e

spring:
  jackson:
    serialization-inclusion: NON_EMPTY
    serialization:
      write-empty-json-arrays: false